jbosstools/jbosstools-build-ci

- readme.adoc
just to show usage of toc.
Do we need to keep master updated ? shuoldnt master just have a top readme saying "deprecated" ?
> use proper level titles + toc

- util/cleanup/jbosstools-cleanup.sh
make sure all dirs contain content; if not, remove them;check that tools@***:/***/mars/snapshots/builds/jbosstools-server_master//2015-06-12_17-51-19-B785//all/repo/ exists, or else 'File not found'
> JBIDE-20090 

- publish/stage.sh
JBIDE-20904 add support for JBDS publishing steps ; add warnings when no update site to publish
> JBIDE-20904 add support for JBDS publishing steps 

- util/cleanup/jbosstools-cleanup.sh
JBIDE-22876 #resolve remove 'JBoss Tools Builds - ' prefix from name of generated composite sites
> JBIDE-22876 #resolve remove 'JBoss Tools Builds - ' prefix from name of generated composite sites

- util/getProjectRootPomParents.sh
JBIDE-22728 enable getProjectRootPomParents.sh to be able to create root pom and branch creation scriptlet
> JBIDE-22728 enable getProjectRootPomParents.sh to be able to create root pom and branch creation scriptlet

- util/velocity.py
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> JBIDE-24319 - Create a script to get intermediate velocity reports for the cabal call

- pom.xml
- publish/checkStagingURLs.sh
Signed-off-by:...
bump to 4.5.2.AM1-SNAPSHOT
Signed-off-by: nickboldt <nboldt@redhat.com>
> bump to 4.5.2.AM1-SNAPSHOT

- readme.adoc
JBIDE-24674 add checkUnresolvedIssues.py to list of utilities
> JBIDE-24674 add checkUnresolvedIssues.py to list

- util/jbosstools-jenkins.properties
> move up to platform 4.13M1

- util/jbosstools-jenkins.properties
> JBIDE-26800 : use 2009-09.M3 builds

- util/jbosstools-jenkins.properties
> JBIDE-26809: Update 4.13.0.AM1 TP for 2019-09.RC1

- util/jbosstools-jenkins.properties
> JBIDE-26842: Update 4.13.0.Final Target Platform for 2019-09.GA

- util/getProjectRootPomParents.sh
> fix PYTHON_CMD initialization.

- util/jbosstools-jenkins.properties
> JBIDE-26972 : Update 4.14.0.AM1 Target Platform for 2019-12.GA

- .gitignore
- util/jbosstools-jenkins.properties
> JBIDE-27089 : Update 4.15.0.AM1 Target Platform for 2020-03.GA

- util/getProjectSHAs.sh
> JBIDE-27149: use token to access GitHub

- util/getProjectSHAs.sh
> JBIDE-27149: fix curl authorization header for GH

- util/cleanup/jbosstools-cleanup.sh
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> JBIDE-27161: jbosstools-cleanup script is bound to 201x years

- util/jbosstools-jenkins.properties
> JBIDE-27253: Update 4.16.0.AM1 Target Platform for 2020-06.M2

- util/jbosstools-jenkins.properties
> JBIDE-27253: update plaform url

- util/jbosstools-jenkins.properties
> JBIDE-27290 : update TP

- util/jbosstools-jenkins.properties
> JBIDE-27290: update TP for 2020-06.RC2

- util/jbosstools-jenkins.properties
> JBIDE-27327 : Update 4.16.0.Final Target Platform for 2020-06 GA

- util/jbosstools-jenkins.properties
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> JBIDE-27429: Update 4.17.0.AM1 Target Platform for 2020-09.M2

- util/jbosstools-jenkins.properties
> JBIDE-27453: Update 4.17.0.AM1 Target Platform for 2020-09 RC1

- util/jbosstools-jenkins.properties
> JBIDE-27466: Update 4.17.0.Final TP for 2020-09

- util/cleanup/jbosstools-cleanup-files.sh
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> Handle files with spaces in cleanup script

- util/jbosstools-console-log-parser.txt
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> FUSETOOLS-3444 FUSETOOLS-3445 - fix character to escape

- util/jbosstools-jenkins.properties
- util/verifyTarget.sh
> JBIDE-27651: Update 4.19.0.AM1 Target Platform for 2021-03

- maven-settings.xml
Signed-off-by: Ondrej Dockal <odockal@redhat.com>
> Add maven settings.xml file, fixes JBIDE-27663

- util/jbosstools-jenkins.properties
> Fix epp package location after 2021-03 release

- util/jbosstools-jenkins.properties
> JBIDE-27776: Update 4.19.0.Final Target Platform for 2021-03

- util/jbosstools-jenkins.properties
> JBIDE-27975: update TP for 2021-09 M3

- util/jbosstools-jenkins.properties
> JBIDE-28008: Update 4.21.0.Final Target Platform for 2021-09 GA

- util/jbosstools-jenkins.properties
> JBIDE-28343: prepare 4.23.0.AM1 TP update

- util/jbosstools-jenkins.properties
> JBIDE-28343: Update 4.23.0.AM1 Target Platform for 2022-03 RC1

- util/getProjectSHAs.sh
> fix jenkins URL

- publish/rsync.sh
- publish/stage.sh
first iteration is to use the new rsync server before moving to sftp.
> JBIDE-28423: migrate rsync scripts.

- util/jbosstools-jenkins.properties
> JBIDE-28467: Update 4.24.0.AM1 Target Platform for 2021-06 M2

- publish/publish.sh
- publish/rsync.sh
- readme.adoc
- util/.gitignore
- util/installFromCentral.sh
- util/installFromTarget.sh
- util/jenkinsPost.sh
> JBIDE-28534 : replace Jenkins URL with current

- util/installFromCentral.sh
- util/installFromTarget.sh
- util/jbosstools-console-log-parser.txt
> JBIDE-28599: fix parsing rules

- util/jbosstools-jenkins.properties
> JBIDE-28585: Update 4.25.0.AM1 TP for 2022-09 RC1

- util/jbosstools-jenkins.properties
> JBIDE-28635: Update 4.25.0.Final Target Platform for 2022-09

- util/jbosstools-jenkins.properties
> JBIDE-28733: update TP for 2022-12-M2
